---
title: "Soc Dta Analysis Final Project - exploring"
author: "Marlon Kegel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(visdat)
library(plm)
library(stringr)
library(corrplot)
```

```{r}
# Chicago_payroll <-read.csv("C:/Users/marlo/OneDrive/Desktop/Uni/S8/Applied Machine Learning (STAT3106)/final project/Employee_Payroll.csv")

NYC_payroll <-
  read.csv(
    "C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/payroll/NYC_Payroll_Data__Fiscal_Year_.csv"
  )
```

```{r}
NYC_payroll$Title.Description <- as.factor(NYC_payroll$Title.Description)
NYC_payroll$Agency.Name <- as.factor(NYC_payroll$Agency.Name)

Chicago_payroll$Bureau <- as.factor(Chicago_payroll$Bureau)
Chicago_payroll$Office.Name <- as.factor(Chicago_payroll$Office.Name)
Chicago_payroll$Job.Title <- as.factor(Chicago_payroll$Job.Title)
```

```{r}
levels(NYC_payroll$Agency.Name)

NYC_boundaryagents <- NYC_payroll %>% filter(Agency.Name == c("Police Department", "POLICE DEPARTMENT", "DEPARTMENT OF CORRECTION"))
NYC_boundaryagents$Title.Description <- as.factor(NYC_boundaryagents$Title.Description)
levels(NYC_boundaryagents$Title.Description)

NYC_boundaryagents %>% filter(First.Name == "BRIAN" & str_detect(Last.Name, "RA"))

```

###


## GSS 2006 panel

> Cops etc: 

```{r}
GSS_2006 <- read_sav("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/GSS 2006 panel/GSS2006.sav")

na_per_column <- as.data.frame(colSums(is.na(GSS_2006)))
columns_to_elim <- na_per_column %>% filter(na_per_column == nrow(GSS_2006))
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_2006), columns_to_elim)
GSS_2006 <- GSS_2006 %>% select(columns_to_keep)

# cops + prison guards : isco88_1 == 3450 | isco88_1 == 5162 | isco88_1 == 5163
# private security : sco88_1 == 5169

wave1_boundary <- GSS_2006 %>% filter(isco88_1 %in% c(3450, 5162, 5163, 5169) | isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) | OCC10_1 %in% c(3710,3850,3860,3800,3930,3700) | occ80_1 %in% c(414, 418, 426, 415, 427))
wave1_boundary <- wave1_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco681_3, isco88_1, isco88_2, isco88_3)

wave2_boundary <- GSS_2006 %>% filter(isco88_2 %in% c(3450, 5162, 5163, 5169) | isco681_2 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) | OCC10_2 %in% c(3710,3850,3860,3800,3930,3700) | occ80_2 %in% c(414, 418, 426, 415, 427))
wave2_boundary <- wave2_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco681_3, isco88_1, isco88_2, isco88_3)

wave3_boundary <- GSS_2006 %>% filter(isco88_3 %in% c(3450, 5162, 5163, 5169) | isco681_3 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) | OCC10_3 %in% c(3710,3850,3860,3800,3930,3700) | occ80_3 %in% c(414, 418, 426, 415, 427))
wave3_boundary <- wave3_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco681_3, isco88_1, isco88_2, isco88_3)

# boundaryplus : + isco88_1 == 9152 | isco88_1 == 5112 | isco88_1 == 5111)


boundary_2006 <- union(wave1_boundary, wave2_boundary)

boundary_2006 <- union(boundary_2006, wave3_boundary)

#boundary$isco88_1 <- as.factor(boundary$isco88_1)
#boundary$isco88_2 <- as.factor(boundary$isco88_2)
#boundary$isco88_3 <- as.factor(boundary$isco88_3)
# boundary_2006 <- boundary_2006 %>% mutate(stayed12 = ifelse(isco88_1 == isco88_2, 1, 0), stayed23 = ifelse(isco88_2 == isco88_3, 1, 0), stayed13 = ifelse(stayed12 == 1 & stayed23 == 1, 1, 0))

boundary_2006 <- boundary_2006 %>% filter(is.na(id_2) == F)

```


## GSS 2008 panel

```{r}
GSS_2008 <- read_sav("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/GSS 2008 panel/GSS_2008_panel.sav")

na_per_column <- as.data.frame(colSums(is.na(GSS_2008)))
columns_to_elim <- na_per_column %>% filter(na_per_column == 2023) 
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_2008), columns_to_elim)
GSS_2008 <- GSS_2008 %>% select(columns_to_keep)

wave1_boundary <- GSS_2008 %>% filter(OCC10_1 %in% c(3710,3850,3860,3800,3930,3700) | occ80_1 %in% c(414, 418, 426, 415, 427) | isco88_1 %in% c(3450, 5162, 5163, 5169) | isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899))
wave1_boundary <- wave1_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco88_1, isco88_2, isco88_3)

wave2_boundary <- GSS_2008 %>% filter(OCC10_2 %in% c(3710,3850,3860,3800,3930,3700) | occ80_2 %in% c(414, 418, 426, 415, 427) | isco88_2 %in% c(3450, 5162, 5163, 5169) | isco681_2 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899))
wave2_boundary <- wave2_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco88_1, isco88_2, isco88_3)

wave3_boundary <- GSS_2008 %>% filter(OCC10_3 %in% c(3710,3850,3860,3800,3930,3700) | isco88_3 %in% c(3450, 5162, 5163, 5169))
wave3_boundary <- wave3_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, occ80_2, isco681_1, isco681_2, isco88_1, isco88_2, isco88_3)

boundary_2008 <- union(wave1_boundary, wave2_boundary)

boundary_2008 <- union(boundary_2008, wave3_boundary)

boundary_2008 <- boundary_2008 %>% filter(is.na(id_2) == F)

```


## GSS 2010 panel

```{r}
GSS_2010 <- read_sav("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/GSS 2010 panel/GSS_2010_panel.sav")

na_per_column <- as.data.frame(colSums(is.na(GSS_2010)))
columns_to_elim <- na_per_column %>% filter(na_per_column == nrow(GSS_2010)) 
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_2010), columns_to_elim)
GSS_2010 <- GSS_2010 %>% select(columns_to_keep)

wave1_boundary <- GSS_2010 %>% filter(OCC10_1 %in% c(3710,3850,3860,3800,3930,3700) | occ80_1 %in% c(414, 418, 426, 415, 427) | isco88_1 %in% c(3450, 5162, 5163, 5169) | isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899))
wave1_boundary <- wave1_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, isco681_1, isco88_1, isco88_2, isco88_3)

wave2_boundary <- GSS_2010 %>% filter(OCC10_2 %in% c(3710,3850,3860,3800,3930,3700) | isco88_2 %in% c(3450, 5162, 5163, 5169))
wave2_boundary <- wave2_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, isco681_1, isco88_1, isco88_2, isco88_3)

wave3_boundary <- GSS_2010 %>% filter(OCC10_3 %in% c(3710,3850,3860,3800,3930,3700) | isco88_3 %in% c(3450, 5162, 5163, 5169))
wave3_boundary <- wave3_boundary %>% select(id_1, id_2, id_3, OCC10_1, OCC10_2, OCC10_3, occ80_1, isco681_1, isco88_1, isco88_2, isco88_3)

boundary_2010 <- union(wave1_boundary, wave2_boundary)

boundary_2010 <- union(boundary_2010, wave3_boundary)

boundary_2010 <- boundary_2010 %>% filter(is.na(id_2) == F)

```


## GSS 2020 panel 

```{r}
GSS_2020 <- read_sav("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/GSS 2020 panel/gss2020panel.SAV")

na_per_column <- as.data.frame(colSums(is.na(GSS_2020)))
columns_to_elim <- na_per_column %>% filter(na_per_column == nrow(GSS_2020)) 
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_2020), columns_to_elim)
GSS_2020 <- GSS_2020 %>% select(columns_to_keep)

wave1a_boundary <- GSS_2020 %>% filter(OCC10_1A %in% c(3710,3850,3860,3800,3930,3700) | ISCO88_1A %in% c(3450, 5162, 5163, 5169) | ISCO08_1A %in% c(3355, 5412, 5414, 5413))
wave1a_boundary <- wave1a_boundary %>% select(ID_1A, ID_1B, ID_2, OCC10_1A, OCC10_1B, OCC10_2, ISCO88_1A, ISCO08_1A, ISCO08_1B)

wave1b_boundary <- GSS_2020 %>% filter(OCC10_1B %in% c(3710,3850,3860,3800,3930,3700) | ISCO08_1B %in% c(3355, 5412, 5414, 5413) )
wave1b_boundary <- wave1b_boundary %>% select(ID_1A, ID_1B, ID_2, OCC10_1A, OCC10_1B, OCC10_2, ISCO88_1A, ISCO08_1A, ISCO08_1B)

wave2_boundary <- GSS_2020 %>% filter(OCC10_2 %in% c(3710,3850,3860,3800,3930,3700))
wave2_boundary <- wave2_boundary %>% select(ID_1A, ID_1B, ID_2, OCC10_1A, OCC10_1B, OCC10_2, ISCO88_1A, ISCO08_1A, ISCO08_1B)

boundary_2020 <- union(wave1a_boundary, wave1b_boundary)

boundary_2020 <- union(boundary_2020, wave2_boundary)
boundary_2020 <- boundary_2020 %>% filter(is.na(ID_2) == F)

```


```{r}
boundary_2006 <-
  boundary_2006 %>% mutate(
    is.boundary_1 = case_when(
      isco88_1 %in% c(3450, 5162, 5163, 5169) |
        isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) |
        OCC10_1 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        occ80_1 %in% c(414, 418, 426, 415, 427) ~ 1,
      is.na(isco88_1) &
        is.na(isco681_1) & is.na(OCC10_1) & is.na(occ80_1) ~ NA,
      T ~ 0
    ),
    is.boundary_2 = case_when(
      isco88_2 %in% c(3450, 5162, 5163, 5169) |
        isco681_2 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) |
        OCC10_2 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        occ80_2 %in% c(414, 418, 426, 415, 427) ~ 1,
      is.na(isco88_2) &
        is.na(isco681_2) & is.na(OCC10_2) & is.na(occ80_2) ~ NA,
      T ~ 0
    ),
    is.boundary_3 = case_when(
      isco88_3 %in% c(3450, 5162, 5163, 5169) |
        isco681_3 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) |
        OCC10_2 %in% c(3710, 3850, 3860, 3800, 3930, 3700) ~ 1,
      is.na(isco88_3) &
        is.na(isco681_3) & is.na(OCC10_3) ~ NA,
      T ~ 0
    )
  ) %>% select(id_1, id_2, id_3, is.boundary_1, is.boundary_2, is.boundary_3) %>%
  mutate(varies = ifelse(is.boundary_1 != is.boundary_2 | is.boundary_2 != is.boundary_3, 1, 0))


boundary_2008 <-
  boundary_2008 %>% mutate(
    is.boundary_1 = case_when(
      OCC10_1 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        occ80_1 %in% c(414, 418, 426, 415, 427) |
        isco88_1 %in% c(3450, 5162, 5163, 5169) |
        isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) ~ 1,
      is.na(OCC10_1) &
        is.na(occ80_1) & is.na(isco88_1) & is.na(isco681_1) ~ NA,
      T ~ 0
    ),
    is.boundary_2 = case_when(
      OCC10_2 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        occ80_2 %in% c(414, 418, 426, 415, 427) |
        isco88_2 %in% c(3450, 5162, 5163, 5169) |
        isco681_2 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) ~ 1,
      is.na(OCC10_2) &
        is.na(occ80_2) & is.na(isco88_2) & is.na(isco681_2) ~ NA,
      T ~ 0
    ),
    is.boundary_3 = case_when(
      OCC10_3 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        isco88_3 %in% c(3450, 5162, 5163, 5169) ~ 1,
      is.na(OCC10_3) & is.na(isco88_3) ~ NA,
      T ~ 0
    )
  ) %>% select(id_1, id_2, id_3, is.boundary_1, is.boundary_2, is.boundary_3) %>%
  mutate(varies = ifelse(is.boundary_1 != is.boundary_2 | is.boundary_2 != is.boundary_3, 1, 0))
    
boundary_2010 <-
  boundary_2010 %>% mutate(
    is.boundary_1 = case_when(
      OCC10_1 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        occ80_1 %in% c(414, 418, 426, 415, 427) |
        isco88_1 %in% c(3450, 5162, 5163, 5169) |
        isco681_1 %in% c(5821, 5822, 5823, 5829, 5891, 5892, 5899) ~ 1,
      is.na(OCC10_1) &
        is.na(occ80_1) & is.na(isco88_1) & is.na(isco681_1) ~ NA,
      T ~ 0
    ),
    is.boundary_2 = case_when(
      OCC10_2 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        isco88_2 %in% c(3450, 5162, 5163, 5169) ~ 1,
      is.na(OCC10_2) & is.na(isco88_2) ~ NA,
      T ~ 0
    ),
    is.boundary_3 = case_when(
      OCC10_3 %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        isco88_3 %in% c(3450, 5162, 5163, 5169) ~ 1,
      is.na(OCC10_3) & is.na(isco88_3) ~ NA,
      T ~ 0
    )
  ) %>% select(id_1, id_2, id_3, is.boundary_1, is.boundary_2, is.boundary_3) %>%
  mutate(varies = ifelse(is.boundary_1 != is.boundary_2 | is.boundary_2 != is.boundary_3, 1, 0))

boundary_2020 <-
  boundary_2020 %>% mutate(
    is.boundary_1 = case_when(
      OCC10_1A %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        ISCO88_1A %in% c(3450, 5162, 5163, 5169) |
        ISCO08_1A %in% c(3355, 5412, 5414, 5413) |
        OCC10_1B %in% c(3710, 3850, 3860, 3800, 3930, 3700) |
        ISCO08_1B %in% c(3355, 5412, 5414, 5413) ~ 1,
      is.na(OCC10_1A) &
        is.na(ISCO88_1A) &
        is.na(ISCO08_1A) & is.na(OCC10_1B) & is.na(ISCO08_1B) ~ NA,
      T ~ 0
    ),
    is.boundary_2 = case_when(
      OCC10_2 %in% c(3710, 3850, 3860, 3800, 3930, 3700) ~ 1,
      is.na(OCC10_2) ~ NA,
      T ~ 0
    )
  ) %>% select(ID_1A, ID_1B, ID_2, is.boundary_1, is.boundary_2)

```



### subjective class identification

```{r}

class06 <- GSS_2006 %>% filter(id_1 %in% boundary_2006$id_1) %>% select(id_1, class_1, class_2, class_3)
class06 <- class06 %>% full_join(boundary_2006, by = "id_1") %>% select(id_1, class_1, class_2, class_3, is.boundary_1, is.boundary_2, is.boundary_3)

class06 <- class06 %>%
  pivot_longer(
    cols = -id_1,
    names_to = c(".value", "wave"),
    names_sep = "_"
  ) %>% mutate(
    t = case_when(wave == 1 ~ 2006,
                  wave == 2 ~ 2008,
                  wave == 3 ~ 2010,
                  T ~ NA),
    id = paste0(id_1, "_06")
  ) %>%
  select(-c(id_1, wave))

class08 <- GSS_2008 %>% filter(id_1 %in% boundary_2008$id_1) %>% select(id_1, class_1, class_2, class_3)
class08 <- class08 %>% full_join(boundary_2008, by = "id_1") %>% select(id_1, class_1, class_2, class_3, is.boundary_1, is.boundary_2, is.boundary_3)

class08 <- class08 %>%
  pivot_longer(
    cols = -id_1,
    names_to = c(".value", "wave"),
    names_sep = "_"
  ) %>% mutate(
    t = case_when(wave == 1 ~ 2008,
                  wave == 2 ~ 2010,
                  wave == 3 ~ 2012,
                  T ~ NA),
    id = paste0(id_1, "_08")
  ) %>%
  select(-c(id_1, wave))

class10 <- GSS_2010 %>% filter(id_1 %in% boundary_2010$id_1) %>% select(id_1, class_1, class_2, class_3)
class10 <- class10 %>% full_join(boundary_2010, by = "id_1") %>% select(id_1, class_1, class_2, class_3, is.boundary_1, is.boundary_2, is.boundary_3)

class10 <- class10 %>%
  pivot_longer(
    cols = -id_1,
    names_to = c(".value", "wave"),
    names_sep = "_"
  ) %>% mutate(
    t = case_when(wave == 1 ~ 2010,
                  wave == 2 ~ 2012,
                  wave == 3 ~ 2014,
                  T ~ NA),
    id = paste0(id_1, "_10")
  ) %>%
  select(-c(id_1, wave))

class20 <- GSS_2020 %>% filter(ID_2 %in% boundary_2020$ID_2) %>% select(ID_1A, ID_1B, ID_2, CLASS_1A, CLASS_1B, CLASS_2)
class20 <- class20 %>% full_join(boundary_2020, by = c("ID_1A", "ID_1B", "ID_2")) 

class20 <- class20 %>%
   mutate(
     cohort = ifelse(is.na(ID_1A), "2018", "2016"),
     id_1 = ifelse(cohort == "2016", ID_1A, ID_1B),
     id_2 = ID_2, 
     class_2 = CLASS_2,
     class_1 = ifelse(cohort == "2016", CLASS_1A, CLASS_1B)
   ) %>% select(!c(ID_1A, ID_1B, ID_2, CLASS_1A, CLASS_1B, CLASS_2))

class20 <- class20 %>%
  pivot_longer(
    cols = -c(id_1, id_2, cohort),
    names_to = c(".value", "wave"),
    names_sep = "_"
  ) %>% mutate(
    t = case_when(
      wave == 1 & cohort == "2016" ~ 2016,
      wave == 1 & cohort == "2018" ~ 2018,
      wave == 2 ~ 2020,
      T ~ NA
    ),
    id = case_when(
      cohort == "2016" ~ paste0(id_1, "_16"),
      cohort == "2018" ~ paste0(id_1, "_18")
    )
  ) %>%
  select(-c(id_1, id_2, wave, cohort))

class <- union(class06, class08)
class <- union(class, class10)
class <- union(class, class20)

class <- na.omit(class)

subj.class.id <- plm(class ~ is.boundary, index = c("id"), model = "within", data = class)
summary(subj.class.id)

summary(lm(class ~ is.boundary, data = class))

class.alt <- class %>%
  arrange(id, t) %>%
  group_by(id) %>%
  mutate(is.boundary = cummax(is.boundary)) %>%
  ungroup()

summary(plm(class ~ is.boundary, index = c("id"), model = "within", data = class.alt))
summary(lm(class ~ is.boundary, data = class.alt))

```


***
***




> Union membership: 

```{r}
union2006 <- GSS_2006 %>% select(id_1, id_2, id_3, union_1, union_2, union_3)
union2006 <- union2006 %>% filter(is.na(id_2) == F)
union2006 <- union2006 %>% filter((is.na(union_1) + is.na(union_2) + is.na(union_3)) < 2)
union2006 <- union2006 %>% mutate(cohort_year = "2006", union.household_2006 = ifelse(union_1 == 4, 0, 1), union.household_2008 = ifelse(union_2 == 4, 0, 1), union.household_2010 = ifelse(union_3 == 4, 0, 1)) %>% rename(id_2006 = id_1, id_2008 = id_2, id_2010 = id_3, union_2006 = union_1, union_2008 = union_2, union_2010 = union_3)

vis_miss(union2006,
         cluster = TRUE)

union2008 <- GSS_2008 %>% select(id_1, id_2, id_3, union_1, union_2, union_3)
union2008 <- union2008 %>% filter(is.na(id_2) == F)
union2008 <- union2008 %>% filter((is.na(union_1) + is.na(union_2) + is.na(union_3)) < 2)
union2008 <- union2008 %>% mutate(cohort_year = "2008", union.household_2008 = ifelse(union_1 == 4, 0, 1), union.household_2010 = ifelse(union_2 == 4, 0, 1), union.household_2012 = ifelse(union_3 == 4, 0, 1)) %>% rename(id_2008 = id_1, id_2010 = id_2, id_2012 = id_3, union_2008 = union_1, union_2010 = union_2, union_2012 = union_3)

vis_miss(union2008,
         cluster = TRUE)

union2010 <- GSS_2010 %>% select(id_1, id_2, id_3, union_1, union_2, union_3)
union2010 <- union2010 %>% filter(is.na(id_2) == F)
union2010 <- union2010 %>% filter((is.na(union_1) + is.na(union_2) + is.na(union_3)) < 2)
union2010 <- union2010 %>% mutate(cohort_year = "2010", union.household_2010 = ifelse(union_1 == 4, 0, 1), union.household_2012 = ifelse(union_2 == 4, 0, 1), union.household_2014 = ifelse(union_3 == 4, 0, 1)) %>% rename(id_2010 = id_1, id_2012 = id_2, id_2014 = id_3, union_2010 = union_1, union_2012 = union_2, union_2014 = union_3)

vis_miss(union2010,
         cluster = TRUE)

union2020_raw <- GSS_2020 %>% select(ID_1A, ID_1B, ID_2, UNION_1A, UNION_1B, UNION_2, UNION1_1A, UNION1_1B, UNION1_2)
union2020 <- union2020_raw %>% filter(is.na(ID_2) == F)
union2020 <- mutate(union2020, cohort = ifelse(is.na(ID_1A), "2018", "2016"), ID_1 = ifelse(cohort == "2016", ID_1A, ID_1B), UNION_1 = ifelse(cohort == "2016", UNION_1A, UNION_1B), UNION1_1 = ifelse(cohort == "2016", UNION1_1A, UNION1_1B))
union2020 <- union2020 %>% select(! c(ID_1A, ID_1B, UNION_1A, UNION_1B, UNION1_1A, UNION1_1B))
union2020 <- union2020 %>% relocate(ID_1, .before = ID_2) %>% relocate(cohort, .after = ID_1) %>% relocate(UNION_1, .before = UNION_2) %>% relocate(UNION1_1, .before = UNION1_2)
union2020 <- union2020 %>% filter(is.na(UNION_1) != T | is.na(UNION1_1) != T & is.na(UNION_2) != T | is.na(UNION1_2) != T)
union2020 <- union2020 %>% rename(union_2020 = UNION_2) %>% mutate(union.household_1 = ifelse(UNION_1 == 4, 0, 1), union.household_2020 = ifelse(union_2020 == 4, 0, 1))

vis_dat(union2020)
vis_miss(union2020,
         cluster = TRUE)

union2006 %>% filter(is.na(union_2006) != T & is.na(union_2008) != T & is.na(union_2010) != T) %>% group_by(union.household_2006, union.household_2008, union.household_2010) %>% summarize(n())

union2008 %>% filter(is.na(union_2008) != T & is.na(union_2010) != T & is.na(union_2012) != T) %>% group_by(union.household_2008, union.household_2010, union.household_2012) %>% summarize(n())

union2010 %>% filter(is.na(union_2010) != T & is.na(union_2012) != T & is.na(union_2014) != T) %>% group_by(union.household_2010, union.household_2012, union.household_2014) %>% summarize(n())

union2020 %>% filter(is.na(UNION_1) != T & is.na(union_2020) != T) %>% group_by(union.household_1, union.household_2020) %>% summarize(n())

levels(as.factor(union2006$union_1))
levels(as.factor(union2008$union_1))
levels(as.factor(union2010$union_1))
levels(as.factor(union2020$UNION_1))


summary(as.factor(union2006$union_1))
summary(as.factor(union2008$union_1))
summary(as.factor(union2010$union_1))
summary(as.factor(union2020$UNION_1))

```


***
***


```{r}

rm(wave1_boundary, wave1a_boundary, wave1b_boundary, wave2_boundary, wave3_boundary, na_per_column, columns_to_elim, columns_to_keep)

census <- read_dta("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/_ProjectRep/Data/wrkdata/census_akk.dta")

colnames(census)

levels(as.factor(census$year))

```



## GSS Cumulative data 

```{r}
GSS_cum <- read_dta("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/GSS_cumulative_1972-2022/gss_cum.dta")

na_per_column <- as.data.frame(colSums(is.na(GSS_cum)))
columns_to_elim <- na_per_column %>% filter(na_per_column >= 71500) 
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_cum), columns_to_elim)
GSS_cum <- GSS_cum %>% select(columns_to_keep)

GSS_cum$occ10 <- as.factor(GSS_cum$occ10)

summary(GSS_cum$occ10)

M <- cor(GSS_cum)

cor_data <- as.data.frame(as.table(M))

# Name the columns appropriately
names(cor_data) <- c("Row", "Column", "Correlation")

# Filter to avoid redundancy and self-correlation
cor_data <- subset(cor_data, Row != Column)

# Order by absolute correlation
cor_data <- cor_data[order(-abs(cor_data$Correlation)), ]

# Select the top N
top_correlations <- head(cor_data, 100)

# Identify unique variables from the top correlated pairs
top_vars <- unique(c(top_correlations$Row, top_correlations$Column))

# Subset the original correlation matrix to only these variables
filtered_M <- M[top_vars, top_vars]


corrplot(filtered_M, order = "hclust", 
         tl.col = "black", tl.srt = 45, # tweak these parameters as needed
         method = "color", type = "lower")
```



## CPS

```{r}
CPS_apr21 <- read.csv("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/CPS/apr21pub.csv")

levels(as.factor(CPS_apr21$gestfips)) # state
levels(as.factor(CPS_apr21$gtcbsa)) # Metropolitan Statistical Area
levels(as.factor(CPS_apr21$gtco)) # county
```


## ESS CroNOS 2

```{r}
CRONOS2 <- read_sav("C:/Users/marlo/OneDrive/Desktop/Uni/S8/final projects/ESS CroNOS 2/integrated CRONOS2 - ESS10/CRON2_ESS10.sav")



```



***
***

