---
title: "FINAL PROJECT - STAT3106"
author: "Marlon Kegel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(tidymodels)
library(haven)
library(visdat)
library(plm)
library(stringr)
library(corrplot)
library(cluster)     
library(factoextra) 
library(vip) 
library(igraph)
library(foreign)
```



## The data - GSS cumulative file (1972 - 2022)


#### all variables of interest
```{r}

# link: https://drive.google.com/drive/folders/19ENQfUv7-2iV7OGgbHojL2WBl9T3-ETx?usp=drive_link

setwd(
  "C:/Users/marlo/OneDrive/Desktop/Uni/S8/Applied Machine Learning (STAT3106)/final_project/all variables"
)

read.dct <- function(dct, labels.included = "yes") {
  temp <- readLines(dct)
  temp <- temp[grepl("_column", temp)]
  switch(labels.included, yes = {
    pattern <- "_column\\(([0-9]+)\\)\\s+([a-z0-9]+)\\s+(.*)\\s+%([0-9]+)[a-z]\\s+(.*)"
    classes <- c("numeric",
                 "character",
                 "character",
                 "numeric",
                 "character")
    N <- 5
    NAMES <- c("StartPos", "Str", "ColName", "ColWidth", "ColLabel")
  }, no = {
    pattern <- "_column\\(([0-9]+)\\)\\s+([a-z0-9]+)\\s+(.*)\\s+%([0-9]+).*"
    classes <- c("numeric", "character", "character", "numeric")
    N <- 4
    NAMES <- c("StartPos", "Str", "ColName", "ColWidth")
  })
  temp_metadata <- setNames(lapply(1:N, function(x) {
    out <- gsub(pattern, paste("\\", x, sep = ""), temp)
    out <- gsub("^\\s+|\\s+$", "", out)
    out <- gsub('\"', "", out, fixed = TRUE)
    class(out) <- classes[x]
    out
  }), NAMES)
  temp_metadata[["ColName"]] <- make.names(gsub("\\s", "", temp_metadata[["ColName"]]))
  temp_metadata
}

read.dat <- function(dat, metadata_var, labels.included = "yes") {
  read.table(dat, col.names = metadata_var[["ColName"]])
}


GSS_metadata <- read.dct("GSS.dct")
GSS_ascii <- read.dat("GSS.dat", GSS_metadata)
attr(GSS_ascii, "col.label") <- GSS_metadata[["ColLabel"]]
GSS_all <- GSS_ascii

rm(GSS_ascii, GSS_metadata)

# big dataset (72,390 rows and 293 columns) 
# very messy, "-100" = NA / "inapplicable
# look under "https://gssdataexplorer.norc.org/variables/vfilter" to explore variables

sum(apply(GSS_all, 2, is.numeric)) - ncol(GSS_all)

GSS_all[GSS_all <= -70] <- NA
subset_rows <- GSS_all$NUMMEN > 700
GSS_all$NUMMEN[subset_rows] <- NA

sum(GSS_all < 0, na.rm = TRUE)

```


#### demographic variables

```{r}

# link: https://drive.google.com/drive/folders/1EsKz48xpbvJ04dhPyC7hNQze-ANdl_el?usp=drive_link

setwd(
  "C:/Users/marlo/OneDrive/Desktop/Uni/S8/Applied Machine Learning (STAT3106)/final_project/demographic"
)


GSS_metadata <- read.dct("GSS.dct")
GSS_ascii <- read.dat("GSS.dat", GSS_metadata)
attr(GSS_ascii, "col.label") <- GSS_metadata[["ColLabel"]]
GSS_dem <- GSS_ascii

rm(GSS_ascii, GSS_metadata)

sum(apply(GSS_dem, 2, is.numeric)) - ncol(GSS_dem)

GSS_dem[GSS_dem <= -70] <- NA

sum(GSS_dem < 0, na.rm = TRUE)

GSS_dem <- GSS_dem %>% select(!c(MNTLHLTH, STRESS, MATESEX, PAIDSEX, SEXFREQ, BALLOT))

```



#### opinion variables

```{r}

#link: https://drive.google.com/drive/folders/13Gcx3lokcnMmLWtoA2oDTA6Vgh4Ns224?usp=drive_link

setwd(
  "C:/Users/marlo/OneDrive/Desktop/Uni/S8/Applied Machine Learning (STAT3106)/final_project/opinion"
)


GSS_metadata <- read.dct("GSS.dct")
GSS_ascii <- read.dat("GSS.dat", GSS_metadata)
attr(GSS_ascii, "col.label") <- GSS_metadata[["ColLabel"]]
GSS_opin <- GSS_ascii

rm(GSS_ascii, GSS_metadata)

sum(apply(GSS_opin, 2, is.numeric)) - ncol(GSS_opin)

GSS_opin[GSS_opin <= -70] <- NA

sum(GSS_opin < 0, na.rm = TRUE)

GSS_opin <- GSS_opin %>% select(!c(TAX, WRKEARN, WRKENJOY, BALLOT))

```



#### miscellaneous variables

```{r}

#link: https://drive.google.com/drive/folders/1lMWIfpj6drzzgfO_gleIxLs4dfBJbmhz?usp=drive_link

setwd(
 "C:/Users/marlo/OneDrive/Desktop/Uni/S8/Applied Machine Learning (STAT3106)/final_project/miscellaneous"
)


GSS_metadata <- read.dct("GSS.dct")
GSS_ascii <- read.dat("GSS.dat", GSS_metadata)
attr(GSS_ascii, "col.label") <- GSS_metadata[["ColLabel"]]
GSS_misc <- GSS_ascii

rm(GSS_ascii, GSS_metadata, read.dat, read.dct)

sum(apply(GSS_misc, 2, is.numeric)) - ncol(GSS_misc)

GSS_misc[GSS_misc <= -70] <- NA
subset_rows <- GSS_misc$NUMMEN > 700
GSS_misc$NUMMEN[subset_rows] <- NA

sum(GSS_misc < 0, na.rm = TRUE)

GSS_misc <- GSS_misc  %>%
  select(!"BALLOT")

```


## Cleaning

```{r}

na_column_dem <- data.frame(missing = colSums(is.na(GSS_dem)))
mean(na_column_dem$missing) / nrow(GSS_dem)

na_column_opin <- data.frame(missing = colSums(is.na(GSS_opin)))
mean(na_column_opin$missing) / nrow(GSS_opin)

na_column_misc <- data.frame(missing = colSums(is.na(GSS_misc)))
mean(na_column_misc$missing) / nrow(GSS_misc)

```



#### cleaning GSS_dem

```{r}

# removing variables with more than 80% NA
na_column_dem <- data.frame(missing = colSums(is.na(GSS_dem)))
na_column_dem$missing <- as.numeric(na_column_dem$missing)

columns_to_elim <- na_column_dem %>% filter(na_column_dem$missing >= 0.8 * nrow(GSS_dem))   
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(GSS_dem), columns_to_elim)
dem_clean <- GSS_dem %>% select(all_of(columns_to_keep))


# removing rows with NA in more than 30% of columns
na_row_dem <- rowSums(is.na(dem_clean))

threshold <- ncol(dem_clean) * 0.3

dem_clean <- dem_clean[na_row_dem <= threshold, ]


# removing variables with more than 43% NA
na_column_dem <- data.frame(missing = colSums(is.na(dem_clean)))
na_column_dem$missing <- as.numeric(na_column_dem$missing)

columns_to_elim <- na_column_dem %>% filter(na_column_dem$missing >= 0.43 * nrow(dem_clean))   
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(dem_clean), columns_to_elim)
dem_clean <- dem_clean %>% select(all_of(columns_to_keep))

# removing rows with NA in more than 20% of columns
na_row_dem <- rowSums(is.na(dem_clean))

threshold <- ncol(dem_clean) * 0.2

dem_clean <- dem_clean[na_row_dem <= threshold, ]

``` 



#### cleaning GSS_opin

```{r}

# keeping only those observations that are in dem_clean

opin_clean <- semi_join(GSS_opin, dem_clean, by = c("YEAR", "ID_")) 

# removing variables with more than 55% NA
na_column_opin <- data.frame(missing = colSums(is.na(opin_clean)))
na_column_opin$missing <- as.numeric(na_column_opin$missing)

columns_to_elim <- na_column_opin %>% filter(na_column_opin$missing >= 0.54 * nrow(opin_clean))   
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(opin_clean), columns_to_elim)
opin_clean <- opin_clean %>% select(all_of(columns_to_keep))


# removing rows with NA in more than 30% of columns
na_row_opin <- rowSums(is.na(opin_clean))

threshold <- ncol(opin_clean) * 0.3

opin_clean <- opin_clean[na_row_opin <= threshold, ]


# removing variables with more than 31% NA
na_column_opin <- data.frame(missing = colSums(is.na(opin_clean)))
na_column_opin$missing <- as.numeric(na_column_opin$missing)

columns_to_elim <- na_column_opin %>% filter(na_column_opin$missing >= 0.31 * nrow(opin_clean))   
columns_to_elim <- row.names(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(opin_clean), columns_to_elim)
opin_clean <- opin_clean %>% select(all_of(columns_to_keep))

# removing rows with NA in more than 15% of columns
na_row_opin <- rowSums(is.na(opin_clean))

threshold <- ncol(opin_clean) * 0.15

opin_clean <- opin_clean[na_row_opin <= threshold, ]


# join it back
dem_clean <- semi_join(dem_clean, opin_clean, by = c("YEAR", "ID_")) 

``` 



#### cleaning GSS_misc

```{r}

# keeping only those observations that are in dem_clean

misc_clean <- semi_join(GSS_misc, dem_clean, by = c("YEAR", "ID_")) 

# removing variables with more than 20% NA
na_column_misc <- data.frame(missing = colSums(is.na(misc_clean)))
na_column_misc$missing <- as.numeric(na_column_misc$missing)

columns_to_elim <- na_column_misc %>% filter(na_column_misc$missing >= 0.2 * nrow(misc_clean))   
columns_to_elim <- rownames(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(misc_clean), columns_to_elim)
misc_clean <- misc_clean %>% select(all_of(columns_to_keep))


# removing rows with NA in more than 15% of columns
na_row_misc <- rowSums(is.na(misc_clean))

threshold <- ncol(misc_clean) * 0.15

misc_clean <- misc_clean[na_row_misc <= threshold, ]


# join it back
dem_clean <- semi_join(dem_clean, misc_clean, by = c("YEAR", "ID_")) 
opin_clean <- semi_join(opin_clean, misc_clean, by = c("YEAR", "ID_")) 

```

```{r}
# removing rows with NA in more than 10% of columns
na_row_dem <- rowSums(is.na(dem_clean))

threshold <- ncol(dem_clean) * 0.1

dem_clean <- dem_clean[na_row_dem <= threshold, ]

opin_clean <- semi_join(opin_clean, dem_clean, by = c("YEAR", "ID_")) 
misc_clean <- semi_join(misc_clean, dem_clean, by = c("YEAR", "ID_")) 


# joining into all variable dataset 
columns <- colnames(dem_clean)
columns <- c(columns, colnames(opin_clean))
columns <- c(columns, colnames(misc_clean))
columns <- unique(columns)

all_clean <- GSS_all %>% select(all_of(columns))
all_clean <- semi_join(all_clean, dem_clean, by = c("YEAR", "ID_")) 

# removing variables with more than 30% overall NA
na_column_all <- data.frame(missing = colSums(is.na(all_clean)))
na_column_all$missing <- as.numeric(na_column_all$missing)

columns_to_elim <- na_column_all %>% filter(na_column_all$missing >= 0.3 * nrow(all_clean))   
columns_to_elim <- rownames(columns_to_elim)
columns_to_elim <- as.character(columns_to_elim)
columns_to_keep <- setdiff(colnames(all_clean), columns_to_elim)
all_clean <- all_clean %>% select(all_of(columns_to_keep))

# removing rows with NA in more than 30% of all columns
na_row_all <- rowSums(is.na(all_clean))

threshold <- ncol(all_clean) * 0.3

all_clean <- all_clean[na_row_all <= threshold, ]

```


#### Initial PRE-PROCESSING

```{r}

columns_dem <- intersect(colnames(dem_clean), colnames(all_clean))
columns_opin <- intersect(colnames(opin_clean), colnames(all_clean))
columns_misc <- intersect(colnames(misc_clean), colnames(all_clean))

binary_cols <- sapply(all_clean, function(x) length(unique(na.omit(x))) == 2)
binary_cols <- names(binary_cols[binary_cols])
binary_cols

sapply(all_clean[binary_cols], unique)

onetwo_cols <- sapply(all_clean, function(x) all(na.omit(x) %in% c(1, 2)))
onetwo_cols <- names(onetwo_cols[onetwo_cols])

all_clean <- all_clean %>% mutate(across(all_of(onetwo_cols), ~ 2 - .x))

fourfive_cols <- sapply(all_clean, function(x) all(na.omit(x) %in% c(4, 5)))
fourfive_cols <- names(fourfive_cols[fourfive_cols])
fourfive_cols

all_clean <- all_clean %>% mutate(across(all_of(fourfive_cols), ~ 5 - .x))

all_clean <- all_clean %>%
  mutate(across(all_of(c("WRKSTAT", "OCC10", "INDUS10", "MARITAL", "SPWRKSTA", "SPOCC10", "SPIND10", "PAOCC10", "RACE", "RES16", "REG16", "MOBILE16", "FAMILY16", "PARBORN", "GRANBORN", "REGION", "RELIG", "RELIG16", "FUND16", "SPREL", "HEALTH", "OWNGUN", "PHONE", "PAPRES10", "PASEI10", "PRESTG10", "SEI10", "SPPRES10", "SPSEI10", "ID_", "CLASS_", "UNION_", "PARTYID", "NATROAD", "NATSOC", "NATMASS", "NATPARK", "COURTS", "HELPFUL", "FAIR", "TRUST", "GETAHEAD", "XMARSEX", "HOMOSEX", "TAX", "FUND", "HAPPY", "SATJOB", "LIFE", "SATFIN", "FINALTER", "PISTOL", "SHOTGUN", "RIFLE", "CONFINAN", "CONBUS", "CONCLERG", "CONEDUC", "CONFED", "CONLABOR", "CONPRESS", "CONMEDIC", "CONTV", "CONJUDGE", "CONSCI", "CONLEGIS", "CONARMY")), factor))

all_clean <- all_clean %>% mutate(OCC10 = as.factor(substr(as.character(OCC10), 1, 2)), 
                                  PAOCC10 = as.factor(substr(as.character(PAOCC10), 1, 2)), 
                                  SPOCC10 = as.factor(substr(as.character(SPOCC10), 1, 2)), 
                                  INDUS10 = as.factor(substr(as.character(SPOCC10), 1, 2)),
                                  SPIND10 = as.factor(substr(as.character(SPOCC10), 1, 2)))

dem_clean <- all_clean %>% select(all_of(columns_dem))
opin_clean <- all_clean %>% select(all_of(columns_opin))
misc_clean <- all_clean %>% select(all_of(columns_misc))


```


```{r}
na_column_dem <- data.frame(missing = colSums(is.na(dem_clean)))
mean(na_column_dem$missing) / nrow(dem_clean)

na_column_opin <- data.frame(missing = colSums(is.na(opin_clean)))
mean(na_column_opin$missing) / nrow(opin_clean)

na_column_misc <- data.frame(missing = colSums(is.na(misc_clean)))
mean(na_column_misc$missing) / nrow(misc_clean)

```


#### Exploratory Data Analysis

```{r}

sum(is.na(all_clean)) / length(unlist(all_clean))
colSums(is.na(all_clean))

na_count_per_row <- rowSums(is.na(all_clean))
na_count_per_row <- as.factor(na_count_per_row)
summary(na_count_per_row)

dem1 <- dem_clean %>% select(1:20)
dem2 <- dem_clean %>% select(21:40)
dem3 <- dem_clean %>% select(41:70)
vis_miss(dem1)
vis_miss(dem2)
vis_miss(dem3)


opin1 <- opin_clean %>% select(1:21)
opin2 <- opin_clean %>% select(22:40)
opin3 <- opin_clean %>% select(40:68)
vis_miss(opin1)
vis_miss(opin2)
vis_miss(opin3)

vis_miss(misc_clean)

nearZeroVar(all_clean)


numeric1 <- sapply(dem1, is.numeric)

# Subset the data frame to only numeric columns
cor_matrix <- cor(dem1[, numeric1], use = "pairwise.complete.obs")

corrplot(
  cor_matrix,
  method = "color",
  type = "upper",
  order = "hclust",
  addCoef.col = "black",
  tl.col = "black",
  tl.srt = 45
)

numeric2 <- sapply(dem2, is.numeric)

# Subset the data frame to only numeric columns
cor_matrix <- cor(dem2[, numeric2], use = "pairwise.complete.obs")

corrplot(
  cor_matrix,
  method = "color",
  type = "upper",
  order = "hclust",
  addCoef.col = "black",
  tl.col = "black",
  tl.srt = 45
)

numeric3 <- sapply(dem3, is.numeric)

# Subset the data frame to only numeric columns
cor_matrix <- cor(dem3[, numeric3], use = "pairwise.complete.obs")

corrplot(
  cor_matrix,
  method = "color",
  type = "upper",
  order = "hclust",
  addCoef.col = "black",
  tl.col = "black",
  tl.srt = 45
)

```


#### DATA SPLITTING

```{r}
index <- createDataPartition(dem_clean$CLASS_, p = 0.75, list = FALSE)
dem_train <- dem_clean[index, ]
dem_test <- dem_clean[-index, ]

blueprint <- recipe(CLASS_ ~ ., data = dem_train) %>%
  
             step_string2factor(all_nominal_predictors()) %>%
             
             step_nzv(all_predictors()) %>%
  
             step_impute_knn(all_predictors()) %>%
  
             step_center(all_numeric_predictors()) %>%
  
             step_scale(all_numeric_predictors()) %>%
             
             step_dummy(all_nominal_predictors())


blueprint_prep <- prep(blueprint, training = dem_train)
dem_train <- bake(blueprint_prep, new_data = dem_train)
dem_test <- bake(blueprint_prep, new_data = dem_test)
```

### XG BOOST



### SUPPORT VECTOR MACHINE 



### ARTIFICIAL NEURAL NETWORK